### ISSUE TITLE
overlord-iv-dub : no video formats found

### ISSUE THREAD

**Issue by digitalw00t** [karl0ss/GoGoDownloader#10]
I get this from both the Downloader and the CLI version as well.

"480 not found for ep1 checking for next best"
"Files Downloaded: 0file [00:00, ?file/s]"

I can download through the web page though.

**Comment by karl0ss** [comment]
Have you added your login deatils to the config.json

**Comment by digitalw00t** [comment]
Yup.  I can pull from others with no issues.  Just not this one.

**Comment by karl0ss** [comment]
as in just that show? I will have a look for you in the next couple days if its only that show not working...

**Comment by digitalw00t** [comment]
Yeah, so far that's the only one.  It's odd to have just one do this I know.  Fyi.. worked for episode 2.
