### ISSUE TITLE
Exception: User is not logged in, make sure account has been activated

### ISSUE THREAD

**Issue by MJ0230** [karl0ss/GoGoDownloader#11]
After providing the credentioals on the config file I am still not able to download. I tried one-piece. Error message is:

`Exception: User is not logged in, make sure account has been activated`

In the app.log it seems, that the user is found though:

```
root - INFO - Config.json loaded
root - INFO - Config loaded and XXXXX username found
root - INFO - episode searched for one-piece
```

The user is active and on the site I am able to login.

**Comment by DeadlyMagikarps** [comment]
You may need to change the config.json file as described in the ReadMe file. 

Under **CurrentGoGoAnimeDomain**. They keep changing it, so it's likely not "**gg**" anymore. Looking at it now, it says "**tel**".

**Comment by MJ0230** [comment]
Thanks. That solved the problem. but I got a new one:

```
Traceback (most recent call last):
  File "C:\Users\Moritz\Downloads\GoGoDownloader-3.2.0\GoGoDownloader.py", line 176, in <module>
    gogodownloader(config)
  File "C:\Users\Moritz\Downloads\GoGoDownloader-3.2.0\GoGoDownloader.py", line 156, in gogodownloader
    result = gogo.file_downloader(dl_links)
  File "C:\Users\Moritz\Downloads\GoGoDownloader-3.2.0\backend.py", line 188, in file_downloader
    dl = Downloader(
TypeError: Downloader.__init__() got an unexpected keyword argument 'headers'
```

**Comment by Arctic4161** [comment]
> Thanks. That solved the problem. but I got a new one:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Moritz\Downloads\GoGoDownloader-3.2.0\GoGoDownloader.py", line 176, in <module>
>     gogodownloader(config)
>   File "C:\Users\Moritz\Downloads\GoGoDownloader-3.2.0\GoGoDownloader.py", line 156, in gogodownloader
>     result = gogo.file_downloader(dl_links)
>   File "C:\Users\Moritz\Downloads\GoGoDownloader-3.2.0\backend.py", line 188, in file_downloader
>     dl = Downloader(
> TypeError: Downloader.__init__() got an unexpected keyword argument 'headers'
> ```

I have fixed this issue in my fork and have requested a pull request to pass it onto Karl0ss. If you want a quick fix just download the backend.py from my fork. I'm sure Karl0ss will pass it onto his CLI tool soon though

**Comment by MJ0230** [comment]
Working now. Thanks!
