### ISSUE TITLE
Crashing?

### ISSUE THREAD

**Issue by Mongerto97** [karl0ss/GoGoDownloader#8]
When I tried executing the script, I'm only able to get up to the point of choosing to download all episode or not. It crashes right after that, probably when trying to download. Do you know how I can fix this?

**Comment by karl0ss** [comment]
Have you added your username and password to the config file? 

sorry it took so long to respond, i didn't get a notification...

**Comment by Mongerto97** [comment]
Hahaha, it's fine lol, I don't really mind it

Yeaa, I did, I don't know what else is wrong

**Comment by karl0ss** [comment]
Can you tell me what show your are trying to get, maybe the format you have entered to find it? as it would imply it can't find the list of episdes...

**Comment by Arctic4161** [comment]
Seems to be with the log in. I can not get it to log me in using the config. Running it in python it gives this Exception: User is not logged in, make sure account has been activated. But the account is activated and logged in on the web browser. Is it necessary to have the user log in?

**Comment by Arctic4161** [comment]
Got it to work. Not sure what the issue was tbh. I would suggest changing line 124 though, in backend.py under user_logged_in_check, to use the {self.config['CurrentGoGoAnimeDomain']} instead of a hardcoded domain for the log in check. 

Another cool feature if i may suggest would be to check https://gogoanime.news/ for the list of domains and just check them for the user instead of having to input a domain under the config for the usable domains for gogo anime. It works well, good work

**Comment by karl0ss** [comment]
Glad you got it working, I will have a look at making the changes you suggested, must admit, thought i had done the first one alredy.

edit - just checked the code here, and it would appear that I did already push that fix 2 months ago? maybe you need to repull...

**Comment by Mongerto97** [comment]
Hii, sorry I haven't been opening up github lately. I tried Pokemon XY and XYZ, but I also tried dress up darling. I think it's a problem with all of the anime? Btw the github crashes after answering the question if I want to download all of the episodes or not.

**Comment by Arctic4161** [comment]
> 

I downloaded your release is where I found that code. I'll re-download and see what it says though

**Comment by Arctic4161** [comment]
Yeah it was fixed on march 12th and the relesse is from the 28th so the release just isn't up to date yet

**Comment by Arctic4161** [comment]
> Hii, sorry I haven't been opening up github lately. I tried Pokemon XY and XYZ, but I also tried dress up darling. I think it's a problem with all of the anime? Btw the github crashes after answering the question if I want to download all of the episodes or not.

I almost guarentee its the login. Login is after episode selection. Make sure you have an account at the domain you are using and that the email is verified. Then wait a few hours and try again.

**Comment by karl0ss** [comment]
I'll make a new release and add some more updated logging, maybe I'll make a "how to use video" as well.

Sorry guys
